# Generated by Django 4.0.4 on 2022-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('header', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(null=True, upload_to='images/')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.ImageField(null=True, upload_to='images/')),
                ('video', models.FileField(null=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('length', models.CharField(max_length=30, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(null=True, upload_to='images/')),
                ('author_name', models.CharField(max_length=255)),
            ],
        ),
    ]
